- name: Install MariaDB package (Kali)
  tags: kali, db, mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Kali"

- name: Install MariaDB package (Ubuntu)
  tags: db, mariadb, ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
